export const IS_FETCHING = "IS_FETCHING";
export const POSTS_FETCHED = "POSTS_FETCHED";
export const STORE_SUBREDDIT = "STORE_SUBREDDIT";
export const STORE_AFTER = "STORE_AFTER";
export const STORE_BEFORE = "STORE_BEFORE";
export const NEW_POSTS_FETCHED = "NEW_POSTS_FETCHED";
export const MORE_POSTS_FETCHED = "MORE_POSTS_FETCHED";
